### ISSUE TITLE
How do I use it for remote development?

### ISSUE THREAD

**Issue by striveBin** [vollborn/jetbrains-gateway-ssh#2]
Hello, I am doing remote development, it can be deployed on the server, when I use remote development to connect to it, how do I use it?

**Comment by vollborn** [comment]
Hey there! It's pretty straight forward - I've just set it up locally for a quick run through.

Once you opened Jetbrains Gateway, you should see a window something like this:

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/3eb1a706-2028-4861-8ddb-3479dfae1b3e)

Add a new project...

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/9e61fea3-127e-4d43-9de2-24dbe121f5f5)

Then add a connection, something like this (update the values to your environment ofc):

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/b21a499f-ed44-4dc1-b202-6d1a5665cc61)

Once added, select the connection and click "Check Connection and Continue":

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/0ffcc66c-da49-475f-9f04-fd3c97bbd33b)

Then you can select your desired IDE and project directory. It should be located under /opt/home - thats the mounted directory.

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/2cd855bf-9836-4955-994c-7abc0f23d54e)

Just click "Start IDE and Connect", and you should be up and running!

![grafik](https://github.com/vollborn/jetbrains-gateway-ssh/assets/67763683/e1054738-b6ad-4739-9c63-985e9b221d3c)
